<a href="https://colab.research.google.com/github/jyothishx/Introduction-to-Python/blob/main/pandas_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
supermarket = files.upload()

Saving Supermarket_sales.csv to Supermarket_sales.csv


In [6]:
import pandas

In [12]:
dataframe = pandas.read_csv('Supermarket_sales.csv')
print(dataframe.tail(8))

       No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6

In [11]:
print(dataframe.head(10))

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       

In [13]:
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [15]:
dataframe.loc[4]

No                                         5
InvoiceID                        373-73-7910
Branch                                     A
City                                  Yangon
Customertype                          Normal
Gender                                  Male
Productline                Sports and travel
Unitprice                              86.31
Quantity                                   7
Tax                                  30.2085
Total                               634.3785
Date                                2/8/2019
Time                                   10:37
Payment                              Ewallet
cogs                                  604.17
gross_margin_percentage             4.761905
gross_iincome                        30.2085
Rating                                   5.3
Name: 4, dtype: object

In [17]:
dataframe['City'].head()

0       Yangon
1    Naypyitaw
2       Yangon
3       Yangon
4       Yangon
Name: City, dtype: object

In [19]:
dataframe[['City', 'Branch', 'Quantity']]

City Branch  Quantity
0       Yangon      A         7
1    Naypyitaw      C         5
2       Yangon      A         7
3       Yangon      A         8
4       Yangon      A         7
..         ...    ...       ...
995  Naypyitaw      C         1
996   Mandalay      B        10
997     Yangon      A         1
998     Yangon      A         1
999     Yangon      A         7

[1000 rows x 3 columns]

In [24]:
dataframe = dataframe.drop(['Tax'],axis=1)

KeyError: ignored

In [25]:
print(dataframe.head())

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   
4       Sports and travel      86.31         7  634.3785   2/8/2019  10:37   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   7

In [27]:
dataframe = dataframe.drop([2],axis=0)
print(dataframe.head())

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   
4       Sports and travel      86.31         7  634.3785   2/8/2019  10:37   
5  Electronic accessories      85.39         7  627.6165  3/25/2019  18:30   

   Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  Ewallet  522.83                 4.761905        26.1415     9.1  
1     Cash   76.40        

In [35]:
dataframe.Unitprice.idxmax()

122

In [33]:
print(dataframe.loc[122])

No                                       123
InvoiceID                        219-22-9386
Branch                                     B
City                                Mandalay
Customertype                          Member
Gender                                  Male
Productline                Sports and travel
Unitprice                              99.96
Quantity                                   9
Total                                944.622
Date                                3/9/2019
Time                                   17:26
Payment                          Credit card
cogs                                  899.64
gross_margin_percentage             4.761905
gross_iincome                         44.982
Rating                                   4.2
Name: 122, dtype: object


In [37]:
minimum = dataframe.Unitprice.idxmin()
minimum_price = dataframe.loc[minimum]
print(minimum_price)

No                                       945
InvoiceID                        333-23-2632
Branch                                     A
City                                  Yangon
Customertype                          Member
Gender                                  Male
Productline                Health and beauty
Unitprice                              10.08
Quantity                                   7
Total                                 74.088
Date                               3/28/2019
Time                                   20:14
Payment                                 Cash
cogs                                   70.56
gross_margin_percentage             4.761905
gross_iincome                          3.528
Rating                                   4.2
Name: 944, dtype: object


In [39]:
dataframe.Unitprice.mean()

55.681481481481484

In [43]:
dataframe.loc[dataframe['Customertype'] == 'Normal'].head()

No    InvoiceID Branch       City Customertype  Gender  \
1    2  226-31-3081      C  Naypyitaw       Normal  Female   
4    5  373-73-7910      A     Yangon       Normal    Male   
5    6  699-14-3026      C  Naypyitaw       Normal    Male   
7    8  315-22-5665      C  Naypyitaw       Normal  Female   
12  13  365-64-0515      A     Yangon       Normal  Female   

               Productline  Unitprice  Quantity     Total       Date   Time  \
1   Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
4        Sports and travel      86.31         7  634.3785   2/8/2019  10:37   
5   Electronic accessories      85.39         7  627.6165  3/25/2019  18:30   
7       Home and lifestyle      73.56        10  772.3800  2/24/2019  11:38   
12  Electronic accessories      46.95         5  246.4875  2/12/2019  10:25   

    Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
1      Cash   76.40                 4.761905         3.8200     9.6  
4   Ewallet  604.17                 4.761905        30.2085     5.3  
5   Ewallet  597.73                 4.761905        29.8865     4.1  
7   Ewallet  735.60                 4.761905        36.7800     8.0  
12  Ewallet  234.75                 4.761905        11.7375     7.1

In [44]:
dataframe.loc[dataframe['Gender'] == 'Male'].head()

No    InvoiceID Branch       City Customertype Gender  \
3    4  123-19-1176      A     Yangon       Member   Male   
4    5  373-73-7910      A     Yangon       Normal   Male   
5    6  699-14-3026      C  Naypyitaw       Normal   Male   
11  12  529-56-3974      B   Mandalay       Member   Male   
13  14  252-56-2699      A     Yangon       Normal   Male   

               Productline  Unitprice  Quantity     Total       Date   Time  \
3        Health and beauty      58.22         8  489.0480  1/27/2019  20:33   
4        Sports and travel      86.31         7  634.3785   2/8/2019  10:37   
5   Electronic accessories      85.39         7  627.6165  3/25/2019  18:30   
11  Electronic accessories      25.51         4  107.1420   3/9/2019  17:03   
13      Food and beverages      43.19        10  453.4950   2/7/2019  16:48   

    Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
3   Ewallet  465.76                 4.761905        23.2880     8.4  
4   Ewallet  604.17                 4.761905        30.2085     5.3  
5   Ewallet  597.73                 4.761905        29.8865     4.1  
11     Cash  102.04                 4.761905         5.1020     6.8  
13  Ewallet  431.90                 4.761905        21.5950     8.2

In [48]:
import numpy as np

In [49]:
student_marks_BA = [12,14,10]
marks = np.array(student_marks_BA)
print(marks)

[12 14 10]


In [52]:
studentmarks = [[12,14,16],[34,53,67],[13,29,21]]
marks = np.array(studentmarks)
print(marks)

[[12 14 16]
 [34 53 67]
 [13 29 21]]


In [53]:
studentmarks = [[35,54,],[12,16],[53,67],[13,29]]
marks = np.array(studentmarks)
print(marks)

[[35 54]
 [12 16]
 [53 67]
 [13 29]]


In [54]:
marks.shape

(4, 2)

In [55]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
np.arange(50,60)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [59]:
np.arange(50,60,2)

array([50, 52, 54, 56, 58])

In [61]:
np.arange(70,100,3)

array([70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [63]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [65]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [66]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
identityarray = np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [68]:
identityarray = np.eye(10,10)
print(identityarray)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [69]:
len(identityarray)

10

In [70]:
firstarray = np.array([[49,42,54],[23,42,89],[32,11,45],[21,67,87]])
print(firstarray)

[[49 42 54]
 [23 42 89]
 [32 11 45]
 [21 67 87]]


In [71]:
secondarray = firstarray.reshape(3,4)
print(secondarray)

[[49 42 54 23]
 [42 89 32 11]
 [45 21 67 87]]


In [73]:
thirdarray = secondarray.reshape(6,2)
print(thirdarray)

[[49 42]
 [54 23]
 [42 89]
 [32 11]
 [45 21]
 [67 87]]


In [76]:
values = np.random.randint(1,3,5)
print(values)

[1 2 1 1 1]


In [78]:
values = np.random.randint(44,88,6)
print(values)

[46 58 49 57 45 52]


In [79]:
values = np.random.randint(25,50,(4,3))
print(values)

[[34 28 46]
 [32 44 41]
 [43 44 45]
 [36 42 47]]
